---
title: Анализ и визуализация многомерных данных с использованием R
description: Презентации к курсу Анализ и визуализация многомерных данных с использованием R
---
 
## О курсе

### Цель и задачи курса

Цель курса — научить решать с точки зрения статистики различные типы исследовательских задач в биологии (сравнение и группировка объектов; различение и разделение групп; определение места объекта/группы в ранее описанной системе). После освоения материалов курса вы сможете критически оценивать корректность применения методов статистики в научных статьях, самостоятельно анализировать данные с использованием скриптов на языке статистического программирования R, представлять в наглядном виде результаты анализов, интерпретировать их и представлять в виде научного отчета.

### Расписание и контакты

1й и 2й парой в четверг и в пятницу, начиная со 2 марта.

Инструкторы: 

- Варфоломеева Марина Александровна -  marina.nikolaeva[]gmail.com
- Хайтов Вадим Михайлович - polydora[]rambler.ru
- Тамберг Юта Юрьевна - yutamberg[]gmail.com

### Задания, дедлайны и оценки

(1) Короткие тесты (10 минут) в конце каждой лекции, кроме самой первой --- 30 баллов. Каждый тест из 2 вопросов, т.е. всего 30 вопросов. Каждый правильный ответ приносит 1 балл.

(2) Домашние задания по анализу данных --- 30 баллов. Срок выполнения --- 1 неделя (прислать по e-mail). За каждое домашнее задание можно получить 10 баллов. За сданное в срок задание один дополнительный балл (т.е. 33 балла за 3 правильных задания в срок). Минимальный набор файлов в решенном задании --- это отчет и код.

- [Критерии оценки домашних заданий](evaluation_criteria.html)
- [Пример решения домашнего задания](example-report.zip)
- [Правила хорошего кода](coding_practices.html)

(3) В конце курса будет финальный тест --- 40 баллов (всего 20 вопросов, каждый правильный ответ приносит 2 балла).

Итоговая оценка:

- Выше 60 баллов - зачет
- 60-69 баллов => «удовлетворительно»; 70-79% => «хорошо»; 80 и больше => «отлично»

### Пересдачи заданий

По пропущенным темам будут дополнительные вопросы в тесте в конце курса.

## Ссылки и ресурсы

- [Исходный код в RMarkdown](http://github.com/varmara/multivar)
- [Другие ресурсы и книги для изучения R и статистики](resources.html)

<!--

- [Как и где можно найти помощь с R и статистикой](more_help.html)

-->
