---
title: Презентации и данные
---

## 1. Знакомство с многомерными данными. nMDS, envfit, ordisurf

```{r eval=FALSE}
install.packages("vegan")
```

- Презентация [html](01_1_multivariate_data_and_dissimilarities.html) | [pdf](01_1_multivariate_data_and_dissimilarities.pdf)
- [код R](01_1_multivariate_data_and_dissimilarities.R)
- Данные [Protein.txt](data/Protein.txt) 

- Презентация [html](01_2_nMDS.html) 
- [код R](01_2_nMDS.R)
- Данные [dolg_abundance.txt](data/dolg_abundance.txt) | [dolg_hydrology.txt](data/dolg_hydrology.txt)

**данные для самостоятельной работы**   
- Обилие полихет на литорали Белого моря [Polychaetes_species.csv](data/Polychaetes_species.csv) | параметры среды [Polychaeta_env.csv](data/Polychaeta_env.csv)  
*Оригинальные данные В. М. Хайтова*   

- растительные сообщества во франции La Mafragh (Annaba, Algérie)  [mafragh_species.csv](data/mafragh_species.csv) | параметры среды [mafragh_env.csv](data/mafragh_env.csv)   
Данные из работы  *de Belair, G. and Bencheikh-Lehocine, M. (1987) Composition et déterminisme de la végétation d'une plaine côtière marécageuse : La Mafragh (Annaba, Algérie). Bulletin d'Ecologie, 18, 393–407.* 


- Деревья на острове Barro Colorado [BCI_species.csv](data/BCI_species.csv) | параметры среды [BCI_env.csv](data/BCI_env.csv)   
Данные из работы *Condit, R, Pitman, N, Leigh, E.G., Chave, J., Terborgh, J., Foster, R.B., Nuñez, P., Aguilar, S., Valencia, R., Villa, G., Muller-Landau, H.C., Losos, E. & Hubbell, S.P. (2002). Beta-diversity in tropical forest trees. Science 295, 666–669.*




<!-- - Данные: -->
<!--     - [IQ_brain.csv](data/IQ_brain.csv) -->

## 2. Тест Мантела, ANOSIM, SIMPER

- Презентация [html](02_1_Mantel_correlation-based_methods.html)
- [код R](02_2_Mantel_correlation-based_methods.R)
- Данные [Coordinates.txt](data/Coordinates.txt) | 


- Презентация [html](02_2_ANOSIM_SIMPER.html)
- [код R](02_1_ANOSIM_SIMPER.R)
- Данные [mussel_beds.csv](data/mussel_beds.csv) | [ASCAM.csv](data/ASCAM.csv) 

**данные для самостоятельной работы**   
- Сообщества макробентоса в экспериментах с искусственно созданными друзами мидий [mussel_experiment.csv](data/mussel_experiment.csv) 
Данные из работы *Хайтов В. М.Бровкина Ю.Б. Механизмы заселения друз Mytilus edulis Linnaeus, 1758 (Bivalvia: Mytilidae) обитателями беломорского песчаного пляжа // БИОЛОГИЯ МОРЯ, 2014. — Vol. 40, — № 4. — P. 302-308*   

- Сообщества макробентоса в друзах мидий [mussel_patches.csv](data/mussel_patches.csv) 
Данные из работы *Хайтов В. М., Артемьева А. В., Фокин М. В., Яковис Е. Л. Структурно-динамическая организация консорциев друз Mytilus edulis на литорали губы Долгой острова Большого Соловецкого. Ч. II. Структура и динамика сообщества, связанного с друзами  Вестн. С.-Петерб. ун-та. Сер. 3. 2002. Вып. 4 (№ 27). С. 18−29.*   





## 3. PERMANOVA

## 4. Кластерный анализ

## 5. Основы матричной алгебры. SVD.

## 6. Анализ главных компонент (Principal Component Analysis, PCA). PCA в геометрической морфометрии

## 7. Анализ избыточности (Redundancy analysis, RDA)

## 8. Корреспондентный анализ (Corespondence Analysis, CA) и анализ главных компонент

## 9. Канонический корреспондентный анализ (Canonical Correspondence Analysis, CCA)

