graph LR
A(Исходные  <br/>данные) --"vegdist()"--> B(Матрица  <br/>коэффициентов различия <br/>в т.ч. неевклидовых)
B --"betadisper()"--> C("PCoA<br/>центроиды и координаты точек <br/>Евклидово пространство")
C --> D(Внутригрупповые  <br/>дисперсии)
